### ISSUE TITLE
Crear documento con temas más importantes de cada libro que les ofrecimos en el bloque I.

### ISSUE THREAD

**Issue by ahroncich7** [ahroncich7/Trabajo-Grupal-ISPC_2#7]
Acá deberíamos repartirnos y asignarnos el trabajo de armar un pequeño esquema/resumen/cuadro conceptual de cada capítulo del material del bloque 1. Estoy averiguando si eso incluye todas las asignaturas (Ética y Deont., Base de Datos, Met. ágiles, etc.) o solo el concerniente a éste tema (Met. Ágile) => https://acceso.ispc.edu.ar/mod/book/view.php?id=22421
Por favor, comenten acá mismo y vamos repartiéndonos la tarea. También hay que ir moviendo las tarjetas en el Project, en la Board Kanban.

**Comment by dunca2022** [comment]
https://github.com/dunca2022/CV.git este es mi  CV  y quiero  que me añadan entendieron???

**Comment by ahroncich7** [comment]
> https://github.com/dunca2022/CV.git este es mi CV y quiero que me añadan entendieron???

Hola Duncan. Estas en el Sprint0, en el issue puntual referido a otra actividad, no a la de CV.

**Comment by dunca2022** [comment]
ah!!! pero tienen que ser específico porque yo no entiendo nada me dicen por donde me tengo meter

**Comment by dunca2022** [comment]
perdón quise  poner, por donde tengo que  entrar?

**Comment by dunca2022** [comment]
me pueden volver a poner como colaborador

**Comment by dunca2022** [comment]
quisas por accidente lo borre no se tanto ingles

**Comment by dunca2022** [comment]
donde se encuentra?

**Comment by dunca2022** [comment]
la que me mandaste  me dice que es invalida

**Comment by ahroncich7** [comment]
No te hagas drama. Tenes asignada las tareas como miembro del equipo asi que no hay inconveniente. Te sugiero que mires los videos para entender como funciona github. Si queres ir haciendo "la tarea", agarra uno de los títulos del material de Metodologías ágiles y hace un pequeñisimos resumen de los puntos fuertes de ese capítulo. Después lo vamos poniendo en comun y hacemos el archivo para cumplir con este primer sprint

**Comment by dunca2022** [comment]
bueno  gracias  compañero

**Comment by dunca2022** [comment]
yo ya tengo listo en un pdf, un trabajo de metodologías agiles, lo hice como un  pequeño mapa conceptual

**Comment by ahroncich7** [comment]
> yo ya tengo listo en un pdf, un trabajo de metodologías agiles, lo hice como un pequeño mapa conceptual

Adjuntalo acá y lo vemos

**Comment by dunca2022** [comment]
[Metodologías agile.pdf](https://github.com/ahroncich7/Trabajo-Grupal-ISPC_2/files/9006483/Metodologias.agile.pdf)

**Comment by dunca2022** [comment]
así quedo bien ? es  lo que yo hice y entendí .
sigo mañana

**Comment by ahroncich7** [comment]
Lo veo bien Duncan. Creo que podemos agregarlo como archivo al repo
